version: "3"

services:
  nodejs:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mundodosteclados.tk/"

  reverse-proxy:
    image: traefik:v1.7
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
